version: '3'

services:
  server:
    build: ./back
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./back:/dist/back
    command: yarn start

  client:
    build: ./front
    environment:
      - PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./front/src:/dist/front/src
      - ./front/public:/dist/front/public
    links:
      - server
    command: yarn start
